name: Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      enableGithub:
        description: 'Publish on Github release'
        required: true
        type: boolean
      

jobs:
  create-artifact:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Parse latest changelog
        run: |
          cat CHANGELOG.md | node script/changelog.js > CHANGELOG-latest.md
      - name: Check
        run: |
          cat Release.txt
          cat CHANGELOG-latest.md
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            Release.txt
            CHANGELOG-latest.md
  
  ckeck-values:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.ref }}
          echo ${{ github.event_name}}
          echo ${{ github.event_name == 'workflow_dispatch'}}
          echo ${{ github.event.inputs.enableGithub == true }}
          echo ${{ github.event.inputs.enableGithub }}
          echo ${{ startsWith(github.ref, 'refs/tags/') }}

  publish-github:
    runs-on: ubuntu-20.04
    needs: [create-artifact]
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/') && github.event.inputs.enableGithub == true)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: release
      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG-latest.md
          files: |
            Release.txt


