on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Parse latest changelog
        run: |
          cat CHANGELOG.md | node script/changelog.js > CHANGELOG-latest.md
      - name: Check
        run: |
          cat Release.txt
          cat CHANGELOG-latest.md
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            Release.txt
            CHANGELOG-latest.md

  publish-github:
    runs-on: ubuntu-20.04
    needs: [create-artifact]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: release
      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG-latest.md
          files: |
            Release.txt


