on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - uses: actions/checkout@v2
      - id: tag_desc
        run: |
          ref=${{ github.event.pull_request.head.ref }}
          tag=`echo "$ref" | sed 's/release\///'`
          echo "::set-output name=ref::$ref"
          echo "::set-output name=tag::$tag"
      - run: |
          git fetch origin ${{ steps.tag_desc.outputs.ref }}
          git checkout ${{ steps.tag_desc.outputs.ref }}
          git tag ${{ steps.tag_desc.outputs.tag }}
          git push origin ${{ steps.tag_desc.outputs.tag }}
