name: Tag
on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  auto-tag:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx semantic-release --no-ci
  manual-tag:
    runs-on: ubuntu-20.04
    if: github.event.workflow_dispatch == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx semantic-release --no-ci
