name: Test package
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - run: npm ci
