name: Trigger Release
on:
  workflow_dispatch:

jobs:
  release-pr:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo $GH_TOKEN
          git config --local user.signingkey $GH_TOKEN
      - run: npm ci
      - run: npm run bump
      - id: pr_desc
        run: |
          version=v$(npx -c 'echo $npm_package_version')
          branch=release/$version
          pr_title="Release $version"
          echo "::set-output name=branch::$branch"
          echo "::set-output name=pr_title::$pr_title"
      - run: |
          git checkout -B ${{ steps.pr_desc.outputs.branch }}
          git commit -S -m "chore: bump ${{ steps.pr_desc.outputs.version }}"
          git push origin ${{ steps.pr_desc.outputs.branch }}
      - run: gh pr create -B main -t "${{ steps.pr_desc.outputs.pr_title }}" -b "" -l release

